[package]
name = "anno_1800_mod_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
itertools = "0.13.0"
roxmltree = "0.20.0"
walkdir = "2.5.0"
