# add name of the workflow
name: Rust CI

# add the event that triggers the workflow
on:
  push:
    tags:
      - v[0-9]+.*

# add the jobs that the workflow will run
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: anno_1800_mod_creator
          token: ${{ secrets.GITHUB_TOKEN }}