# add name of the workflow
name: Rust CI

# add the event that triggers the workflow
on:
  push:
    tags:
      - "v*"

# add the jobs that the workflow will run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --all --release

      # add the executable to the release
      - name: Archive release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/anno_1800_mod_creator.exe
        